#!/bin/bash
datafile="${1}.dataset"
clusfile="${1}.${2}"
statfile="${1}.${2}.stats"
# extract title from the first line of the cluster file in the form "# TITLE(...)"
title=$(sed '1q;d' $clusfile | tr '()' ' ' | awk '{ print $2 }')
bcubed=($(sed '2q;d' $statfile))
silhouette=($(sed '5q;d' $statfile))
gnuplot -p <<- EOP
    # terminal
    set terminal png size 800,800
    set size square
    set output '${clusfile}.png'
    
    # colors
    set palette defined ( \
        0 '#222222',\
        1 '#377EB8',\
        2 '#4DAF4A',\
        3 '#984EA3',\
        4 '#FF7F00',\
        5 '#FFFF33',\
        6 '#A65628',\
        7 '#F781BF',\
        8 '#E41A1C')
    unset colorbox
        
    # title and axes
    #set title 'Clusters - ${title}' font 'sans, 24'
    set xlabel sprintf("Pr: %5.3f   Rc: %5.3f   Sl: %5.3f", ${bcubed[1]}, ${bcubed[2]}, ${silhouette[3]}) font 'sans, 36'
    #unset xlabel
    set xrange [-1:1]
    set xtics 2,2
    unset ylabel
    set yrange [-1:1]
    unset ytics
    
    # styles
    set style line 1 linecolor palette pointtype 7 pointsize 1.2
    
    # plot
    plot '< paste ${datafile} ${clusfile}' using 2:3:5 with points notitle ls 1;
EOP