#!/bin/bash
filename=${1}
# extract title from the first line in the form "#\t...\tTITLE"
title=$(sed '1q;d' $filename | awk -F$'\t' '{ print $3 }')
# extract x-axis label from the second line in the form "LABEL\t..."
label=$(sed '2q;d' $filename | awk -F$'\t' '{ print $1 }')
gnuplot -p <<- EOP
    # terminal
    set terminal png size 800,450
    set output '${filename}.png'
    
    # title and axes
    set title 'Performance - ${title}' font 'sans, 16'
    set xlabel '$label' font 'sans, 12'
    set ylabel "Runtime (ms)" font 'sans, 12'
    set ytics nomirror
    set yrange [0:]
    set y2label "Memory Useage (kB)" font 'sans, 12'
    set y2tics nomirror
    set y2range [0:]
    set autoscale fix
    
    # plot styles
    set key top left reverse Left
    set style line 1 linecolor rgb 'green'  pointtype 5  pointsize 0.6
    set style line 2 linecolor rgb 'blue'   pointtype 7  pointsize 0.6
    
    # plot
    plot '${filename}' using 1:(\$4/1000000) with linespoints title "Runtime" ls 1, \
        '' using 1:(\$5/1024) with linespoints title "Memory" ls 2 axes x1y2;
EOP